/* eslint-disable @next/next/no-img-element */
import React, { useRef, useState } from 'react'
import Header from '../components/Header'
import Head from 'next/head'
import Button from '../components/Button'
import { useRouter } from "next/navigation"
import { ClipLoader } from "react-spinners"
import axios from "axios"

const Contact = () => {
    const router = useRouter()
    const nameRef = useRef()
    const numberRef = useRef()
    const mailRef = useRef()
    const msgRef = useRef()
    const [load, setLoad] = useState(false)

    const sendMail = async () => {
        setLoad(true)
        const data = {
            email: mailRef.current.value,
            phone_number: numberRef.current.value,
            first_name: nameRef.current.value,
            message: msgRef.current.value
        }

        console.log(data)


        axios.post("https://backend.getlinked.ai/hackathon/contact-form", data).then((res) => {
            console.log(res)
            setLoad(false)
            mailRef.current.value = ''
            numberRef.current.value = ''
            nameRef.current.value = ""
            msgRef.current.value = ""
        }).catch((err) => {
            console.log(err)
        })
    }


    return (


        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=' bg-[#150E28] h-full relative overflow-hidden md:py-[20px]  '>
                {/* The blur lightning at the background  starts here */}
                <div className='bg-[#903AFF] blur-[80px] md:blur-[100px] h-[120px] w-[200px] md:h-[150px] md:w-[300px] rounded-full absolute top-[18%] left-[5%] md:top-[25%] md:left-[15%] z-0'>

                </div>
                {/* The blur lightning at the background  ends here */}

                {/* The second blur lightning at the background  starts here */}
                <div className='bg-[#903AFF] blur-[50px] md:blur-[120px] h-[40px] w-[100px] md:h-[350px] md:w-[200px] rounded-full absolute md:bottom-[-180px] lg:bottom-[0px] md:right-[-50px] lg:right-[50px] z-0 right-[-120px] bottom-0'>

                </div>

                {/* The second blur lightning at the background  starts here */}

                <div className='hidden lg:block'>
                    <Header contact="true" />
                </div>

                <div className=' lg:hidden pt-[30px] pl-[30px] '
                    onClick={() => {
                        router.push("/")
                    }}
                >
                    <img src='/images/bvck.svg' alt="start" className='w-[23px] h-[23px] ' />
                </div>
                <div className=' md:w-[70%] mx-auto  relative  md:py-[40px] '>
                    {/* Absolute positions of the stars */}
                    <div className='md:flex justify-between hidden py-[40px] '>
                        <img src='/images/sata.svg' alt="start" className='md:w-[21px] md:h-[25px]  top-[15%] left-[20%]' />

                        <img src="/images/star-gray.svg" alt="star" className='w-[13px] h-[15px] md:w-[26px] md:h-[32px]  bottom-[55%] right-[5%]   ' />

                    </div>
                    <img src="/images/star.svg" alt="star" className='w-[13px] h-[15px] md:w-[26px] md:h-[32px] absolute bottom-[5%] right-[-5%]   ' />

                    <img src="/images/sata.svg" alt="fire" className='bottom-[25%] right-[55%] absolute w-[13px] h-[15px] md:w-[26px] md:h-[32px] ' />


                    {/* Absolute position of the stars ends here */}



                    <div className=' md:flex justify-between relative '>
                        <div className='mt-[30px] hidden lg:block '>
                            <div className='flex flex-col gap-[20px] text-white'>
                                <h1 className='text-[32px] text-[#D434FE] clash-semi '>Get in touch</h1>

                                <p>Contact <br /> information</p>

                                <h1 className=' text-[14px] text-white '>27,Alara Street <br /> Yaba 100012 <br /> Lagos State</h1>

                                <h1>Call Us : 07067981819</h1>

                                <h1>we are open from Monday-Friday <br /> 08:00am - 05:00pm</h1>

                                <div>
                                    <h1 className='text-[#D434FE] mb-[10px]  ' >Share On</h1>
                                    <div className='flex space-x-[16px]'>
                                        <img src="/images/ig.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                        <img src="/images/x.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                        <img src="/images/fb.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                        <img src="/images/in.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div className='contact-bg md:w-full lg:w-[55%]  py-[70px]'>
                            <div className='w-[80%] mx-auto flex flex-col  p-[px] gap-[30px]'>
                                <h1 className=' text-[#D434FE] text-[20px] clash-semi font-[100] '>Questions or need assistance? <br /> Let us know about it! </h1>

                                <p className='text-white text-[14px] lg:hidden' > Email us below to any question related <br /> to our event</p>


                                <input type='text' ref={nameRef} placeholder='First Name' className=' bg-transparent text-white p-[10px] border border-white rounded-md ' />


                                <input type='email' ref={mailRef} placeholder='Email' className=' bg-transparent text-white p-[10px] border border-white rounded-md ' />


                                <input type='text' ref={numberRef} placeholder='Phone number' className=' bg-transparent text-white p-[10px] border border-white rounded-md ' />

                                <textarea rows={5} ref={msgRef} className=' bg-transparent border border-white text-white p-[10px] rounded-md ' placeholder='Message' >

                                </textarea>


                            </div>
                            <div className='flex items-center justify-center mt-[20px] cursor-pointer '
                                onClick={() => {
                                    sendMail()
                                }}
                            >

                                <div className=' inline-block text-[16px] text-white font-[400]  2xl:px-[52px] 2xl:py-[16px] px-[48px] py-[12px] bg-gradient-to-r from-[#D434FE] to-[#903AFF] rounded-sm text-center' >
                                    {load ? <ClipLoader color='#fff' size={20} /> : "Submit"}
                                </div>

                            </div>
                            <div className='mt-[35px] lg:hidden flex flex-col items-center '>
                                <h1 className='text-[#D434FE] mb-[10px]  ' >Share On</h1>
                                <div className='flex space-x-[16px]'>
                                    <img src="/images/ig.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                    <img src="/images/x.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                    <img src="/images/fb.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                    <img src="/images/in.svg" className='w-[24px] h-[24px] ' alt='ig' />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>

        </div>
    )
}

export default Contact