import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import HeroSection from '../components/HeroSection'
import IntroductionSection from '../components/IntroductionSection'
import RulesSection from '../components/RulesSection'
import JudgingSection from '../components/JudgingSection'
import FAQs from '../components/FAQs'
import Timeline from '../components/Timeline'
import Prizes from '../components/Prizes'
import Partners from '../components/Partners'
import Privacy from '../components/Privacy'
import Footer from '../components/Footer'

export default function Home() {
    return (
        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=' bg-[#150E28] '>
              <HeroSection />
              <IntroductionSection />
              <RulesSection />
              <JudgingSection />
              <FAQs />
              <Timeline />
              <Prizes />
              <Partners />
              <Privacy />
              <Footer />
            </main>

        </div>
    )
}
